//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5_3_LAYERS_PROJECT.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVC3KATMANLIDBEntities : DbContext
    {
        public MVC3KATMANLIDBEntities()
            : base("name=MVC3KATMANLIDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Table_Ceza> Table_Ceza { get; set; }
        public virtual DbSet<Table_Haraket> Table_Haraket { get; set; }
        public virtual DbSet<Table_Kasa> Table_Kasa { get; set; }
        public virtual DbSet<Table_Kategori> Table_Kategori { get; set; }
        public virtual DbSet<Table_Kitab> Table_Kitab { get; set; }
        public virtual DbSet<Table_Personel> Table_Personel { get; set; }
        public virtual DbSet<Table_Uyeler> Table_Uyeler { get; set; }
        public virtual DbSet<Tablo_YAZAR> Tablo_YAZAR { get; set; }
        public virtual DbSet<Table_Hakkimizda> Table_Hakkimizda { get; set; }
        public virtual DbSet<Table_ILETISIM> Table_ILETISIM { get; set; }
    }
}
